server:
  port: 3200
spring:
  application:
    name: feign-hystrix
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0  # 全部需要，默认 0.1
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka
feign:
  hystrix:
    enabled: true
# 熔断器DashBoard: actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management:
  endpoints:
    web:
      exposure:
        include: "*"